---
name: Performance Tests

on:
  push:
    paths:
      - 'rules/**'
      - 'tests/**'
      - '.github/**'
  pull_request:
    paths:
      - 'rules/**'
      - 'tests/**'
      - '.github/**'

jobs:
  performance:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        modsec_version: [modsec2-apache]
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Install dependencies"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GO_FTW_VERSION: '0.4.8'
        run: |
          gh release download -R coreruleset/go-ftw v${GO_FTW_VERSION} -p "ftw_${GO_FTW_VERSION}_linux_amd64.tar.gz" -O - | tar -xzvf - ftw

      # check changed files, clone the old rules in folder /old_rules
      # the old rules are used to compare the new rules with the old ones
      - name: "Clone changed rules and corresponding test cases"
        id: "performance_test_init"
        run: |    
          
          num_changed_rules=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -E 'rules/.*\.conf' | wc -l)

          # no rule changes
          if [ $num_changed_rules = 0 ]; then
            echo "num_changed_rules=0" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          
          # copy rule files

          echo "Tracker 1"
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -E 'rules/.*\.conf' > rules-changed.txt

          cat rules-changed.txt

          mkdir rules-before rules-after
          while read -r filename; do
          echo $filename
          echo "Tracker 2"
            git show "${{ github.event.before }}:$filename" > "rules-before/${filename#rules/}"
            git show "${{ github.event.after }}:$filename" > "rules-after/${filename#rules/}"
          done < $(grep -E 'rules/.*\.conf' rules-changed.txt)

          # copy corresponding test files
          mkdir rules-changed-test
          echo "Tracker 3"

          while read -r filename; do
            echo $filename
            req="${filename#rules/}"
            req="${result%.conf}"
            cp -R tests/regression/tests/$req rules-changed-test/$req
          done < $(grep -E 'rules/.*\.conf' rules-changed.txt)

      # performance tests
      - name: "Run performance test for changed rules"
        run: |
          modsec_version=${{ matrix.modsec_version }}
          origin_yaml_path=./tests/docker-compose.yml
          before_yaml_path=before-docker-compose.yml
          after_yaml_path=after-docker-compose.yml

          # create and update yaml
          sed 's/- ..\/rules:\/opt\/owasp-crs\/rules:ro/- .\/rules-before:\/opt\/owasp-crs\/rules:ro/g' $origin_yaml_path > $before_yaml_path
          sed 's/- ..\/rules:\/opt\/owasp-crs\/rules:ro/- .\/rules-after:\/opt\/owasp-crs\/rules:ro/g' $origin_yaml_path > $after_yaml_path

          # test before changes
          docker-compose -f $before_yaml_path up -d "${{ matrix.modsec_version }}"
          docker-compose -f $before_yaml_path logs
          [ $(docker inspect ${{ matrix.modsec_version }} --format='{{.State.Running}}') = 'true' ]
          ./ftw run -d rules-changed-test > raw.go_ftw.before.txt

          # restart, test with after changes
          docker-compose -f ./tests/docker-compose.yml stop "${{ matrix.modsec_version }}"
          docker-compose -f ./tests/docker-compose.yml down
          docker-compose -f $after_yaml_path up -d "${{ matrix.modsec_version }}"
          docker-compose -f $after_yaml_path logs
          [ $(docker inspect ${{ matrix.modsec_version }} --format='{{.State.Running}}') = 'true' ]
          ./ftw run -d rules-changed-test > raw.go_ftw.after.txt

          cat raw.go_ftw.after.txt
          python3 ./test.py          
        if: steps.performance_test_init.outputs.num_changed_rules != '0'
      # @TODO: create report

      - name: "Change permissions if failed"
        if: failure()
        run: |
            # we want to get the audit log, so change permissions (file is only for root on docker)
            sudo chmod 644 tests/logs/${{ matrix.modsec_version }}/modsec_audit.log

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: waf-logs
          path: tests/logs/${{ matrix.modsec_version }}

      - name: Clean docker-compose
        run: |
          docker-compose -f ./tests/docker-compose.yml stop "${{ matrix.modsec_version }}"
          docker-compose -f ./tests/docker-compose.yml down
