---
name: Performance Tests

on:
  push:
    paths:
      - 'rules/**'
      - 'tests/**'
      - '.github/**'
      - '*/**'
  pull_request:
    paths:
      - 'rules/**'
      - 'tests/**'
      - '.github/**'
      - '*/**'

jobs:
  performance:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        modsec_version: [modsec2-apache]
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Install dependencies"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GO_FTW_VERSION: '0.4.8'
        run: |
          gh release download -R coreruleset/go-ftw v${GO_FTW_VERSION} -p "ftw_${GO_FTW_VERSION}_linux_amd64.tar.gz" -O - | tar -xzvf - ftw

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: "Install Poetry"
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: false
          installer-parallel: true

      # check changed files, clone the old rules in folder /old_rules
      # the old rules are used to compare the new rules with the old ones
      - name: "Clone changed rules and corresponding test cases"
        id: "performance_test_init"
        run: |

          poetry install

          BEFORE_COMMIT=${{ github.event.before }}
          AFTER_COMMIT=${{ github.event.after }}

          poetry run collect --test-name pipeline-test --before "$BEFORE_COMMIT" --after "$AFTER_COMMIT" --utils ftw

      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: output
