---
name: Regression Tests

on:
  push:
    paths:
      - 'rules/**'
      - 'tests/**'
      - '.github/**'
  pull_request:
    paths:
      - 'rules/**'
      - 'tests/**'
      - '.github/**'

jobs:
  regression:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        modsec_version: [modsec2-apache]
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Install dependencies"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GO_FTW_VERSION: '0.4.8'
        run: |
          gh release download -R coreruleset/go-ftw v${GO_FTW_VERSION} -p "ftw_${GO_FTW_VERSION}_linux_amd64.tar.gz" -O - | tar -xzvf - ftw

      # check changed files, clone the old rules in folder /old_rules
      # the old rules are used to compare the new rules with the old ones
      - name: "Clone changed rules and corresponding test cases"
        run: |    
          mkdir rules-before rules-after

          echo ${{ github.event.before }}
          echo ${{ github.event.after }}
          
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -E 'rules/.*\.conf'
          # git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -E 'rules/.*\.conf' > rules-changed.txt
          
          # check if any rule is changed
          echo "Tracer 2"
          if [ -s rules-changed.txt ]; then

            echo "Tracer 3"
            while read -r filename; do
              git show "${{ github.event.before }}:$filename" > "rules-before/${filename#rules/}"
              echo "Tracer 4"
              git show "${{ github.event.after }}:$filename" > "rules-after/${filename#rules/}"
            done < rules-changed.txt

            echo "Tracer 5"
            # copy corresponding test files
            mkdir rules-changed-test
            while read -r filename; do
              req="${filename#rules/}"
              req="${result%.conf}"
              cp -R tests/regression/tests/$req rules-changed-test/$req
            done < rules-changed.txt

          else
            echo "no changes on rules"
            exit_with_success
          fi

      # regression tests
      - name: "Run tests for ${{ matrix.modsec_version }}"
        run: |
          mkdir -p tests/logs/${{ matrix.modsec_version }}/{nginx,apache2}
          docker-compose -f ./tests/docker-compose.yml up -d "${{ matrix.modsec_version }}"
          docker-compose -f ./tests/docker-compose.yml logs
          [ $(docker inspect ${{ matrix.modsec_version }} --format='{{.State.Running}}') = 'true' ]
          ./ftw check -d tests/regression/tests
          ./ftw run -d tests/regression/tests --show-failures-only
        env:
          FTW_LOGFILE: './tests/logs/modsec2-apache/error.log'

      # performance tests
      - name: "Run performance test for changed rules"
        run: |    

          if [ ! -s rules-changed.txt ]; then
            echo "skip performance test"
            return
          fi

          # restart, apply customized .conf
          docker-compose -f ./tests/docker-compose.yml stop "${{ matrix.modsec_version }}"
          docker-compose -f ./tests/docker-compose.yml down

          modsec_version=${{ matrix.modsec_version }}
          
          origin_yaml_path=./tests/docker-compose.yml
          before_yaml_path=before-docker-compose.yml
          after_yaml_path=after-docker-compose.yml

          # create and update yaml
          sed 's/- ..\/rules:\/opt\/owasp-crs\/rules:ro/- .\/rules-before:\/opt\/owasp-crs\/rules:ro/g' $origin_yaml_path > $before_yaml_path
          sed 's/- ..\/rules:\/opt\/owasp-crs\/rules:ro/- .\/rules-after:\/opt\/owasp-crs\/rules:ro/g' $origin_yaml_path > $after_yaml_path

          # test before changes
          docker-compose -f $before_yaml_path up -d "${{ matrix.modsec_version }}"
          docker-compose -f $before_yaml_path logs
          [ $(docker inspect ${{ matrix.modsec_version }} --format='{{.State.Running}}') = 'true' ]
          ./ftw run -d rules-changed-test > raw.go_ftw.before.txt

          # restart, test with after changes
          docker-compose -f ./tests/docker-compose.yml stop "${{ matrix.modsec_version }}"
          docker-compose -f ./tests/docker-compose.yml down
          docker-compose -f $after_yaml_path up -d "${{ matrix.modsec_version }}"
          docker-compose -f $after_yaml_path logs
          [ $(docker inspect ${{ matrix.modsec_version }} --format='{{.State.Running}}') = 'true' ]
          ./ftw run -d rules-changed-test > raw.go_ftw.after.txt

          cat raw.go_ftw.after.txt
          python3 ./test.py          

      # @TODO: create report

      - name: "Change permissions if failed"
        if: failure()
        run: |
            # we want to get the audit log, so change permissions (file is only for root on docker)
            sudo chmod 644 tests/logs/${{ matrix.modsec_version }}/modsec_audit.log

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: waf-logs
          path: tests/logs/${{ matrix.modsec_version }}

      - name: Clean docker-compose
        run: |
          docker-compose -f ./tests/docker-compose.yml stop "${{ matrix.modsec_version }}"
          docker-compose -f ./tests/docker-compose.yml down
